<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="hp" ignored="0" name="Test" tests="4" failures="2" timestamp="2021-03-19T16:08:53 IST" time="18.68" errors="0">
  <testcase name="testFail" time="0.017" classname="testng.CaptureScreenshot">
    <failure type="java.lang.AssertionError" message="expected [Online Web Tutorials] but found [W3Schools Online Web Tutorials]">
      <![CDATA[java.lang.AssertionError: expected [Online Web Tutorials] but found [W3Schools Online Web Tutorials]
at testng.CaptureScreenshot.testFail(CaptureScreenshot.java:34)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase name="testPass" time="0.008" classname="testng.CaptureScreenshot"/>
  <testcase name="testcaseFail" time="0.001" classname="testng.Demo1">
    <failure type="java.lang.AssertionError" message="expected [8] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [7]
at testng.Demo1.testcaseFail(Demo1.java:15)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcaseFail -->
  <testcase name="testcasePass" time="0.001" classname="testng.Demo1"/>
</testsuite> <!-- Test -->
